version: '3.8'
services:
  db:
    container_name: wagg_local_database
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
