version: '3.8'
services:
  db:
    container_name: wagg_local_database
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  nodejs:
    container_name: wagg_local_backend
    build: .
    command: ['npm', 'run', 'migration:up:and:run']
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - '.env'

volumes:
  db:
    driver: local
